export interface Post {
    _id:string,
    _createdAt?:string,
    title:string,
    author:{
        name:string,
        image:{
            asset:{
                _ref:string
            }
        },
    },
    'comments':{
        name:string,
        email:string,
        message:string,
        _ref:string,
        _id:string,
        _type:string,
        _updatedAt:string,
        _cretaeAt:string,
        post:{
            _ref:string,
            _type:string
        },
        approved:boolean
    }
    ,
    description:string,
    slug:{
        current:string
    },
    mainImage:{
        asset:{
            _ref:string
        }
    },
    body:[object]
}